name: Deploy to GithubPages

on:
  push:
    branches:
      - master

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Packages
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Deploy
        # https://github.com/marketplace/actions/npm-publish
        uses: JS-DevTools/npm-publish@v2
        with:
          tag-name: "v%s"
          tag-message: "v%s"
          create-tag: "false"
          commit-pattern: "^release.*"
          token: ${{secrets.NPM_TOKEN}}
